### PR TITLE
Added constants file

### PR DESCRIPTION
**Pull request by aulisius**
It is better to keep code readable by encapsulating magic numbers in the
form of enums. Added a keys object with mapping to their keyCodes. No
need of comments like `//space` when the code itself is self-documenting.

- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku-react/blob/master/CONTRIBUTING.md).
- [x] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by anshumanv** [comment]
Nice thinking man. 😄

**Review by anshumanv — APPROVED** [review]
👍

**Review by filoxo — APPROVED** [review]
LGTM, thanks!

**Comment by aulisius** [comment]
Thanks for merging! :D

**Pull request merged**
