### PR TITLE
Prevent disabling last enabled option

### LINKED ISSUE #11: Disabling all preferences may crash app
Currently, disabling all preferences and attempting to play another song (next or prev) will crash the app since the array of track data is now totally empty.

Probably should guard against this by either preventing the last "enabled" option from being disabled if the other 2 are disabled, or by reenabling the first option if all of them are disabled.

### PR DESCRIPTION
**Pull request by jackiewmacharia**
Fixes #11 

#### This PR is for [Anime Name].

- [X] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [X] I have checked my addition locally and it is working and won't break existing entries.
- [X] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku-react/blob/master/CONTRIBUTING.md).
- [X] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by anshumanv** [comment]
Hey @jackiemacharia thanks for contributing here.
I just tested that out locally and it works amazingly well.

**Review by anshumanv — APPROVED** [review]
👍

**Review by filoxo — APPROVED** [review]
❤️ it, thanks for contributing! Happy Hacktoberfest!

**Comment by jackiewmacharia** [comment]
Anytime! Glad I could help.

**Pull request merged**
