### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hey there. I've just optimized your image. It is the same dimensions and quality as before, only it takes up less space now.

\public\img\play.png (0.14%)

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]
:+1:

**Review by filoxo — COMMENTED** [review]
0.14% savings is almost not even significant but it's great to have this sort of thing setup so that it isn't missed.

**Comment by anshumanv** [comment]
In the HTML repo all the icons are replaced by fa icons so, images have to be removed anyway. :stuck_out_tongue:

**Comment by dabutvin** [comment]
👍 happy to help

If you want more prs from ImgBot here, or any of your other projects, feel free to install the GitHub app.

https://github.com/apps/ImgBot

**Pull request merged**
